# miner名称，不填使用电脑名
# miner name, use the computer name without filling in
minerName: "rtx3080ti4-1"
# 在 https://www.hpool.in/center/configuration 找ApiKey
# Find ApiKey at https://www.hpool.in/center/configuration
apiKey: "ironfish-35ad-259f-44dc-85ba4d6fa081"
# 日志配置
# Log configuration
log:
  lv: info
  path: ./log/
  name: miner.log
# x-proxy配置
# x-proxy configuration
server:
  # 一个局域网内，代理只需要开一台就可以了，如代理所在的机器Ip是192.168.1.88，端口9190
  # 下面配置改为
  # xproxy: "http://192.168.1.88:9190"
  # In a local area network, only one proxy is required. For example, the IP of the machine where the proxy is located is 192.168.1.88 and the port is 9190
  # The following configuration is changed to
  # xproxy: "http://192.168.1.88:9190"
  xproxy: ""
# socket 或者是http代理配置
# socket5 or http proxy
proxy:
    # E.g http://127.0.0.1:8888 socks5://127.0.0.1:8888
    url: ""
    username: ""
    password: ""
# 语言选择
# language selection
language: cn
# 线路
# line
line: cn

# 参数配置
# Parameter configuration
extraParams:
  # GPU设备编号
  # GPU device number
  gpuDevice: 0,1,2,3
  # 一次计算个数, 默认 2048000000
  # Calculate the number at a time, the default is 2048000000
  gpuBatchCount: 2048000000
  # 并行数，默认是4
  # Parallel number, the default is 4
  instanceCount: 4
  # CPU绑定间隔
  # CPU binding step
  cpuAffinityStep: 0
  # cpu开始绑定编号
  # cpu start binding number
  cpuAffinityStart: -1